/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addOrUpdateProduct' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSortedProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addOrUpdateProduct' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSortedProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };